services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"

    volumes:
      - sts_sqldata:/var/opt/mssql

volumes:
  sts_sqldata:
