CREATE TABLE [dbo].[AboutPageContent] (
    [id] INT NOT NULL CONSTRAINT [AboutPageContent_id_df] DEFAULT 1,
    [heroEyebrow] NVARCHAR(1000) NOT NULL,
    [heroTitle] NVARCHAR(1000) NOT NULL,
    [heroHighlight] NVARCHAR(1000) NOT NULL,
    [heroSubtitle] NVARCHAR(max) NOT NULL,
    [heroStats] NVARCHAR(max) NOT NULL,
    [serviceCards] NVARCHAR(max) NOT NULL,
    [processEyebrow] NVARCHAR(1000) NOT NULL,
    [processTitle] NVARCHAR(1000) NOT NULL,
    [processSteps] NVARCHAR(max) NOT NULL,
    [founderEyebrow] NVARCHAR(1000) NOT NULL,
    [founderName] NVARCHAR(1000) NOT NULL,
    [founderRole] NVARCHAR(1000) NOT NULL,
    [founderPhoto] NVARCHAR(1000),
    [founderBio] NVARCHAR(max) NOT NULL,
    [founderBullets] NVARCHAR(max) NOT NULL,
    [founderStats] NVARCHAR(max) NOT NULL,
    [teamEyebrow] NVARCHAR(1000) NOT NULL,
    [teamTitle] NVARCHAR(1000) NOT NULL,
    [metricsTitle] NVARCHAR(1000) NOT NULL,
    [metrics] NVARCHAR(max) NOT NULL,
    [reasonsTitle] NVARCHAR(1000) NOT NULL,
    [reasons] NVARCHAR(max) NOT NULL,
    [termsTitle] NVARCHAR(1000) NOT NULL,
    [termsText] NVARCHAR(max) NOT NULL,
    [termsButtonLabel] NVARCHAR(1000) NOT NULL,
    [termsItems] NVARCHAR(max) NOT NULL,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [AboutPageContent_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [updatedAt] DATETIME2 NOT NULL,
    CONSTRAINT [AboutPageContent_pkey] PRIMARY KEY CLUSTERED ([id])
);
